# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_mocha"

# format = '''
# [┌─\(](bold lavender)$username(bold text)$hostname[\)](bold lavender)$fill[\[](bold lavender)$directory[\]](bold lavender)$fill[\[](bold lavender)$git_branch[\]](bold lavender)$fill[\[](bold lavender)$rust$java$haskell$python$nodejs$kotlin[\]](bold lavender)
# [└─](bold lavender)$character
# '''

format = '''
[\(](bold lavender)$username(bold text)[\)](bold lavender)[-\[](bold lavender)$directory[\]](bold lavender)$git_branch$rust$c$java$haskell$python$nodejs$kotlin$nix_shell
(bold lavender)$character
'''

right_format = '''
$cmd_duration
'''

add_newline = true

[cmd_duration]
min_time = 500
show_milliseconds = true
show_notifications = false
min_time_to_notify = 30_000
format = '[$duration](bold yellow)'

[nix_shell]
disabled = false
# impure_msg = '[impure](bold red)'
# pure_msg = '[pure](bold green)'
# unknown_msg = '[unknown](bold yellow)'
# symbol = '❄️' # its the snowflake emoji, i swear
# format = '[-\[](bold lavender)[$symbol $state](bold blue)[\]](bold lavender)'
impure_msg = "[](bold blue)"
pure_msg = "[](bold green)"
unknown_msg = "[](bold yellow)"
symbol = ''
format = '[-\[](bold lavender)$state[\]](bold lavender)'

[fill]
symbol = '─' # ඞ # ─
style = 'bold lavender'

[git_branch]
style = "bold sapphire"
format = '[-\[](bold lavender)[$symbol]($style)[$branch]($style)[\]](bold lavender)'

[directory]
truncation_length = 3
style = "bold mauve"
truncation_symbol = "…/"
format = '[$path]($style)[$read_only]($read_only_style)'

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Developer" = "󰲋"

[username]
show_always = true
style_user = "fg:text"
style_root = "fg:text"
format = '[$user]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:green)' # ❯
error_symbol = '[❯](bold fg:red)' # ❯
vimcmd_symbol = '[❮](bold fg:creen)' # ❮
# vimcmd_replace_one_symbol = '[<-](bold fg:purple)' # ❮
# vimcmd_replace_symbol = '[<-](bold fg:purple)' # ❮
# vimcmd_visual_symbol = '[<-](bold fg:lavender)' # ❮


[nodejs]
symbol = ""
format = '[-\[](bold lavender)[[$symbol( $version)](fg:green)]($style)[\]](bold lavender)'

[rust]
symbol = ""
format = '[-\[](bold lavender)[[$symbol rust-tacular!](fg:peach)]($style)[\]](bold lavender)'

[java]
symbol = ""
format = '[-\[](bold lavender)[[$symbol( $version)](fg:blue)]($style)[\]](bold lavender)'

[kotlin]
symbol = ""
format = '[-\[](bold lavender)[[$symbol( $version)](fg:mauve)]($style)[\]](bold lavender)'

[haskell]
symbol = ""
format = '[-\[](bold lavender)[[$symbol( $version)](fg:mauve)]($style)[\]](bold lavender)'

[python]
symbol = ""
format = '[-\[](bold lavender)[[$symbol( $version)](fg:yellow)]($style)[\]](bold lavender)'




# Palette definitions
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
